baseURL = 'https://faultydaantje.github.io/'
languageCode = 'en'
title = "DVB Engineering Lab"
theme = "hugo-coder"
defaultContentLanguage = "en"

[params]
    colorScheme = "auto"
    author = "DVB"
    description = "3D Printing, Moped Restoration, and Engineering"
    keywords = "blog, developer, engineer, 3dprinting"
    info = "Engineering Student & Maker"
    avatarURL = "images/avatar.jpg" # Place a photo in static/images/avatar.jpg
    enableComments = true

    # Social links for Coder
    [[params.social]]
        name = "Github"
        icon = "fa fa-2x fa-github"
        weight = 1
        url = "https://github.com/Faultydaantje"
        # YouTube Link
    [[params.social]]
        name = "YouTube"
        icon = "fa fa-2x fa-youtube"
        weight = 2
        url = "https://www.youtube.com/@DVB2007"

    # MakerWorld Link
    [[params.social]]
        name = "MakerWorld"
        icon = "fa fa-2x fa-cube" # Using a cube icon to represent 3D models
        weight = 3
        url = "https://makerworld.com/en/@danivbel"

# This theme uses a different menu system
[[menu.main]]
    name = "BLOG"
    weight = 1
    url = "/posts/"

[[menu.main]]
    name = "SYSTEM_LOG"
    url = "/changelog/"
    weight = 2

[[menu.main]]
    name = "ABOUT"
    weight = 3
    url = "/about/"

[[menu.main]]
    name = "GALLERY"
    weight = 4
    url = "/gallery/"

[params.giscus]
        repo = "faultyDaantje/DVB-blog"
        repoId = "R_kgDOSNIm5Q"
        category = "Announcements"
        categoryId = "DIC_kwDOSNIm5c4C7vSF"
        mapping = "pathname"
        strict = "0"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        theme = "preferred_color_scheme" # This matches the Coder dark/light mode
        lang = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true