baseURL = 'https://faultydaantje.github.io/'
languageCode = 'en'
title = "DVB Engineering Lab"
theme = "hugo-coder"
defaultContentLanguage = "en"
relativeURLs = true
canonifyURLs = true

[params]
    colorScheme = "auto"
    author = "DVB"
    description = "3D Printing, Moped Restoration, and Engineering"
    keywords = "blog, developer, engineer, 3dprinting"
    info = "Engineering Student & Maker"
    avatarURL = "images/avatar.jpg" # Place a photo in static/images/avatar.jpg
    enableComments = true

    # Social links for Coder
    [[params.social]]
        name = "Github"
        icon = "fa fa-2x fa-github"
        weight = 1
        url = "https://github.com/Faultydaantje"

# This theme uses a different menu system
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"

[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

[[menu.main]]
    name = "Gallery"
    weight = 3
    url = "/gallery/"

[params.giscus]
        repo = "faultyDaantje/DVB-blog"
        repoId = "R_kgDOSNIm5Q"
        category = "Announcements"
        categoryId = "DIC_kwDOSNIm5c4C7vSF"
        mapping = "pathname"
        strict = "0"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        theme = "preferred_color_scheme" # This matches the Coder dark/light mode
        lang = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true